### ISSUE TITLE
How to handle SIGABRT ?

### ISSUE THREAD

**Issue by NaveenKh** [catchorg/Catch#1005]
## Description

I started using Catch yesterday to build my unit testing cases. Good thing about Catch is that, setup was so easy, I could setup everything in 5 minutes and started writing testcases!! 
Coming to my issue. My application runs in some loop and the normal way of exiting it is by ctrl+c / SIGABRT. But when this happens CATCH says it failed. Is there any way to make normal exit when SIGABRT is received ? I tried handling SIGABRT by calling exit(0) in the handler, but still the testcase fails.
Can you please suggest me how to proceed ?
I tried finding others posts regarding this, but none of them helped. Please advice

**Comment by horenmar** [comment]
You generally cannot. Any structured exception/signal getting all the way to Catch handler is taken as signal of error and the assertion/section/test case is marked as failed. You might try to see what happen when you define `CATCH_CONFIG_NO_POSIX_SIGNALS` as that prevents Catch from installing its own signal handlers.

There is a greater question though, why are you running tests inside an interactive (I presume because it seems to loop endlessly) application?

**Comment by NaveenKh** [comment]
I will try with defining CATCH_CONFIG_NO_POSIX_SIGNALS and let you know results soon.

so my code is like, the application starts and it initializes few stuff and then it goes into loop(there are 2 or 3 threads involved). And there is a timeout every 2 seconds where it does some logging. The application is shutdown after 10 seconds by configuring a timer to terminate the app(I guess it does this by closing all instances and then triggering ctrl+c). I am not the complete owner of this code but this is my understanding about this.

**Comment by NaveenKh** [comment]
I defined  CATCH_CONFIG_NO_POSIX_SIGNALS but program ran and just exited, no output from CATCH was seen :(

**Comment by horenmar** [comment]
Disregard the commit, I wrote down wrong issue number

**Comment by ruipacheco** [comment]
I have a similar issue. Sometimes I run my tests on an IDE and stop once I notice something. I'd like Catch to run any tear down code I defined on my listeners when that happens otherwise I have to do it by hand.
